import { ProductConfiguratorData } from "@/src/types/configurator.types";

export const businessCardsConfig: ProductConfiguratorData = {
  slug: "business-cards",
  title: "Business Cards",
  subtitle: "All of our business cards are printed full colour on 100% recycled papers.",
  description:
    "Communicate that your business is Eco-Friendly with our range of recycled business cards. From 350gsm 100% recycled Uncoated Business cards to brown Kraft Business cards to 350gsm Recycled Silk. Contact us if you need something different at sales@sustainableprintingco.com.au.",
  descriptionTitle: "Premium Uncoated Recycled Business Cards",
  aboutParagraphs: [
    "Sustainable Printing Co was founded to provide artists, brands and businesses with a fully sustainable printing solution. All of our papers are made from 100% post consumer recycled fibre and we use vegetable based inks to further reduce our environmental impact.",
    "We are a family business with over 30 years' experience in the printing industry that is proudly Australian owned and operated. Our facility runs on 100% GreenPower and we are committed to reducing waste at every step of the printing process.",
  ],
  features: [
    "100% post consumer recycled uncoated cards",
    "Excellent printability, colours look great",
    "350gsm Uncoated (natural look and feel)",
    "Perfect to write on",
    "High white finish (without nasty bleaching processes)",
    "Communicates that your business is eco friendly",
    "Option to round corner",
  ],
  faqs: [
  {
    question: "Are your business cards printed in Australia?",
    answer:
      "They sure are, we produce all our printing in our Australian facility. We are a family business with over 30 years' experience in the printing industry that is proudly Australian owned.",
  },

  {
    question:
      "I need my business cards urgently, can you fast track my order?",
    answer:
      "Please contact us at sales@sustainableprinting.com.au for information on how we can fast track your order.",
    boldWords: [
      {
        word:
          "I need my business cards urgently, can you fast track my order?",
      },
      {
        word: "sales@sustainableprinting.com.au",
        href: "mailto:sales@sustainableprinting.com.au",
      },
    ],
  },

  {
    question: "How do I supply artwork?",
    answer:
      "We require a print ready PDF for printing. Please also supply with 3mm bleed and trim marks. For more information on how to set up artwork, please click here",
    boldWords: [
      {
        word: "click here",
        href: "/docs/artwork-specification-guide.pdf",
      },
    ],
  },

  {
    question: "Can I change my business cards size?",
    answer:
      "Absolutely, if you have a custom size card, please inform us and we will trim accordingly. Most standard business cards are 90mm x 55mm. You/your graphic designer is welcome to set the custom size when creating your business card artwork.",
  },

  {
    question: "Do you provide proofs?",
    answer:
      "Yes, we can either print a proof on the stock for you (at an additional cost) or send a PDF proof (no additional cost). Proofing allows you the check the details one last time before final print. Best catch any changes at this stage and resupply artwork if needed. Proofs are generated by request only.",
  },

  {
    question:
      "Does Sustainable Printing print laminated business cards?",
    answer:
      "Yes, we can. We have matt laminates available. Please call 03 9482 2222 or email sales@sustainableprinting.com.au for a quote.",
    boldWords: [
      {
        word: "sales@sustainableprinting.com.au",
        href: "mailto:sales@sustainableprinting.com.au",
      },
    ],
  },

  {
    question: "Is 350gsm your thickest paper?",
    answer:
      "We have thicker stocks available. 350gsm is what we use for our Premium Recycled Business Cards. Please contact 03 9482 2222 or email sales@sustainableprinting.com.au for a quote and more information.",
    boldWords: [
      {
        word: "sales@sustainableprinting.com.au",
        href: "mailto:sales@sustainableprinting.com.au",
      },
    ],
  },

  {
    question: "Do you print circle business cards?",
    answer:
      "Yes, we do, please call 03 9482 2222 or email sales@sustainableprinting.com.au for a quote and more information. We also round corner business cards if you would like a softer looking edge. Select the 'round corner' option when placing your order online.",
    boldWords: [
      {
        word: "sales@sustainableprinting.com.au",
        href: "mailto:sales@sustainableprinting.com.au",
      },
    ],
  },

  {
    question:
      "I need more business cards than what your set prices offer, is this possible?",
    answer:
      "Yes, it is. Please contact us to know let us know your exact requirements and quantity breakdown. Please call 03 9482 2222 or email sales@sustainableprinting.com.au for a quote.",
    boldWords: [
      {
        word:
          "I need more business cards than what your set prices offer, is this possible?",
      },
      {
        word: "sales@sustainableprinting.com.au",
        href: "mailto:sales@sustainableprinting.com.au",
      },
    ],
  },

  {
    question: "Do you offer business card templates?",
    answer:
      "We can assist with the design of your business card if needed. This does incur further charged. Please call 03 9482 2222 or email sales@sustainableprinting.com.au for more information and a quote.",
    boldWords: [
      {
        word: "sales@sustainableprinting.com.au",
        href: "mailto:sales@sustainableprinting.com.au",
      },
    ],
  },

  {
    question: "Can I split quantities for business cards?",
    answer:
      "Yes, that is totally fine, please let us know the quantity split you’re after and we will quote you accordingly. It’s helpful if you can please write the quantity for each person’s card in their file name.",
  },

  {
    question: "Do you still have my artwork on file?",
    answer:
      "Yes, we should have your artwork on file if you have printed with us before. We will send you a proof of the file so you can double check before proceeding to print.",
  },

  {
    question:
      "Do you print business cards with Pantone Inks/Spot Colours?",
    answer:
      "Yes we can, however we will need to quote this separately as it would be printed as a stand-alone job (not with other CMYK cards at the same time). The costs for printing with Pantone Inks can often significantly higher compared to our regular CMYK business card printing.",
  },

  {
    question:
      "Can I please see a sample of your work before proceeding?",
    answer:
      "Yes, we would love to send you some samples, please request a sample pack here",
    boldWords: [
      {
        word:
          "Can I please see a sample of your work before proceeding?",
      },
      {
        word: "request a sample pack here",
        href: "/requestsample",
      },
    ],
  },
],
  designOptions: [
    { value: 1, label: "1 design" },
    { value: 2, label: "2 designs" },
    { value: 3, label: "3 designs" },
    { value: 4, label: "4 designs" },
    { value: 5, label: "5 designs" },
  ],
  quantityOptions: [
    { value: 100, label: "100" },
    { value: 250, label: "250" },
    { value: 500, label: "500" },
    { value: 1000, label: "1,000" },
    { value: 2500, label: "2,500" },
    { value: 5000, label: "5,000" },
  ],
  papers: [
    { id: "ecostar-uncoated", label: "350gsm EcoStar 100% Recycled Uncoated (White)", basePriceMultiplier: 1.0 },
    { id: "recycled-silk", label: "350gsm Recycled Silk", basePriceMultiplier: 1.15 },
    { id: "kraft-brown", label: "300gsm Kraft Brown", basePriceMultiplier: 1.1 },
  ],
  sizes: [
    { id: "standard-au", dimensions: "90 × 55 mm", label: "Standard AU" },
    { id: "slim-au", dimensions: "90 × 55 mm", label: "Slim AU" },
    { id: "eu-intl", dimensions: "85 × 55 mm", label: "EU / Intl" },
    { id: "custom", dimensions: "Custom", label: "Your size" },
  ],
  printingTypes: [
    { id: "double-sided", label: "Double sided", description: "Full colour both sides" },
    { id: "single-sided", label: "Single sided", description: "Full colour front only" },
  ],
  extras: [
    { id: "round-corners", label: "Round corners", priceTiers: [] },
  ],
  // Price per unit at each quantity bracket (ex. GST & delivery)
  pricingTiers: [
    { minQty: 100,  maxQty: 249,  pricePerUnit: 0.099 },
    { minQty: 250,  maxQty: 499,  pricePerUnit: 0.075 },
    { minQty: 500,  maxQty: 999,  pricePerUnit: 0.058 },
    { minQty: 1000, maxQty: 2499, pricePerUnit: 0.045 },
    { minQty: 2500, maxQty: 4999, pricePerUnit: 0.036 },
    { minQty: 5000, maxQty: 99999,pricePerUnit: 0.031 },
  ],
  pricingTable: [],
  deliveryPrice: 9.90,
  gstRate: 0.10,
  relatedProductSlugs: ["adhesive-labels", "greeting-cards", "swing-tags", "brochures"],
  artworkOptions: [
    {
      id: "upload-pdf",
      label: "Upload print-ready PDF",
      description: "I have my own artwork ready to print",
      badge: "RECOMMENDED" as const,
      icon: "upload-pdf" as const,
    },
    {
      id: "upload-later",
      label: "Upload artwork later",
      description: "I'll send my artwork via email after ordering",
      icon: "upload-later" as const,
      contextMessage: "No problem — we'll email you a secure upload link as soon as your order is placed. Production starts once your artwork is approved.",
      contextIcon: "info" as const,
    },
  ],
  paymentMethods: [
    { id: "bank", label: "Direct Bank Transfer", description: "Pay directly via bank transfer.",    icon: "bank" as const, type: "bank" as const },
    { id: "card", label: "Credit Card",          description: "Pay securely using your credit card.", icon: "card" as const, type: "card" as const },
  ],
  bankDetails: {
    accountName:   "Sustainable Printing Co.",
    bank:          "ANZ Bank",
    bsb:           "013412",
    accountNumber: "309431255",
    paymentTerms:  "Payment Required prior to dispatch.",
  },
  paymentNote: "Note: Delivery times are estimates and begin once artwork has been approved. Rural and remote areas may require additional time.",
  deliveryNote: "Delivery times are estimates and begin once artwork has been approved. Rural and remote areas may require additional time.",
  artworkGuidelines: [
    "PDF format preferred (300dpi minimum resolution)",
    "Convert fonts to outlines / curves",
    "Keep important content 5mm from trim edge",
    "Include 3mm bleed on all sides",
    "CMYK colour mode for best results",
    "Embed all linked images at full quality",
  ],
};
